creation_rules:
  # encrypt files using GCP KMS ending in -secret.yaml
  - path_regex: ".*/*-secret.yaml$"
    encrypted_regex: "^(data|stringData)$"
    gcp_kms: projects/myproject/locations/global/keyRings/sops/cryptoKeys/sops-key
  - gcp_kms: projects/myproject/locations/global/keyRings/sops/cryptoKeys/sops-key
