apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-resources
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/lodotek/minikube-olm-argocd
    - https://github.com/argoproj/argocd-example-apps
