apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.test
  repositories: |
    - url: https://github.com/lodotek/minikube-olm-argocd
    - url: https://github.com/argoproj/argocd-example-apps
  ## Enable Kustomize Plugins
  # kustomize.buildOptions: "--enable_alpha_plugins"
