apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
type: Opaque
data:
    admin.password: ENC[AES256_GCM,data:az2vqBXcv+8WnuYgMBh+gXlgz4uvOW7/lUOOU/XqhkLGVYO0PG/6W5zUBQkhbLacimdbvcV+klba/3Fo6AzH297s6+SfHBIXs6ANWeRhpkq73oy2,iv:k2rErtpbPoNJokn6BgGk/H9BiuN56OlaHtw/K1vLHsk=,tag:Lnc/G+sa+e7s2nM7uWwKow==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:+8oFrZRqJ7LNTdzYpAVdA9rUOejvFBJ2MJaJBch1sPw=,iv:WOw+pgaOTPnHwj6u2NxZVI2EGsipFYM38IiH3VScF0o=,tag:tumCF6kDBmfRnW9c0oLWHA==,type:str]
    server.secretkey: ENC[AES256_GCM,data:0l+0KmH0stGAxUdLYf2cqLqShxFqj5kX3No9jHnSbQ18vKXJMy/gRphYb4KJ42owkvCfGluCJSaTXrCq,iv:DqtnH2ePh3L9i0sqLm1D6Alir1sXXFnMg5rVWx/+mFE=,tag:ks96eLQjHmAUR3fGvdMmXg==,type:str]
