apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  labels:
    app.kubernetes.io/component: prometheus-operator
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: kustomize
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-resources

  source:
    path: kube-prometheus-stack
    repoURL: https://github.com/lodotek/minikube-olm-argocd
    targetRevision: prometheus

  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus-operator

  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /spec/validation
      kind: CustomResourceDefinition

    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
