resources:
- namespace.yaml
- catalog-source.yaml
- operator_group.yaml
- subscription.yaml
# - argocd-sa-rolebinding-hack-from-upstream.yaml
# - argocd-w-ingress.yaml

# secretGenerator:
#   - name: argocd-repositories-secret
#     envs:
#       - gh.secret.env
# generatorOptions:
#   disableNameSuffixHash: true
